export const stitches = {
	k: {
		name: "knit",
		abbreviation: "k",
		width: 1,
		symbol: "*",
		description: "knit",
	},
	p: {
		name: "purl",
		abbreviation: "p",
		width: 1,
		symbol: "-",
		description: "purl",
	},
	ktbl: {
		name: "knit through back loop",
		abbreviation: "ktbl",
		width: 1,
		symbol: "*!",
		description: "knit one through back loop",
	},
	ptbl: {
		name: "purl through back loop",
		abbreviation: "ptbl",
		width: 1,
		symbol: "-!",
		description: "purl one through back loop",
	},
	// todo: update all stitch icons !!
	_1x1lc: {
		name: "1/1 left cross",
		abbreviation: "1/1lc",
		width: 2,
		symbol: "\\*",
		description: "slip one stitch onto cable needle and hold in front, knit one, purl one from cable needle",
	},
	_1x1rc: {
		name: "1/1 right cross",
		abbreviation: "1/1rc",
		width: 2,
		symbol: "*/",
		description: "slip one stitch onto cable needle and hold in back, purl one, knit one from cable needle",
	},
	_1x1lpc: {
		name: "1/1 left purl cross",
		abbreviation: "1/1lpc",
		width: 2,
		symbol: "\\-",
		description: "slip one stitch onto cable needle and hold in front, purl one, knit one from cable needle",
	},
	_1x1rpc: {
		name: "1/1 right purl cross",
		abbreviation: "1/1rpc",
		width: 2,
		symbol: "-/",
		description: "slip one stitch onto cable needle and hold in back, knit one, purl one from cable needle",
	},
	_2x1lc: {
		name: "2/1 left cross",
		abbreviation: "2/1lc",
		width: 3,
		symbol: "\\\\*",
		description: "slip two stitches onto cable needle and hold in front, knit one, knit two from cable needle",
	},
	_2x1rc: {
		name: "2/1 right cross",
		abbreviation: "2/1rc",
		width: 3,
		symbol: "*//",
		description: "slip one stitch onto cable needle and hold in back, knit two, knit one from cable needle",
	},
	_2x1lpc: {
		name: "2/1 left purl cross",
		abbreviation: "2/1lpc",
		width: 3,
		symbol: "\\\\-",
		description: "slip two stitches onto cable needle and hold in front, purl one, knit two from cable needle",
	},
	_2x1rpc: {
		name: "2/1 right purl cross",
		abbreviation: "2/1rpc",
		width: 3,
		symbol: "-//",
		description: "slip one stitch onto cable needle and hold in back, knit two, purl one from cable needle",
	},
	_2x2lc: {
		name: "2/2 left cross",
		abbreviation: "2/2lc",
		width: 4,
		symbol: "\\\\**",
		description: "slip two stitches onto cable needle and hold in front, knit two, knit two from cable needle",
	},
	_2x2rc: {
		name: "2/2 right cross",
		abbreviation: "2/2rc",
		width: 4,
		symbol: "**//",
		description: "slip two stitches onto cable needle and hold in back, knit two, knit two from cable needle",
	},
	_2x2lpc: {
		name: "2/2 left purl cross",
		abbreviation: "2/2lpc",
		width: 4,
		symbol: "\\\\--",
		description: "slip two stitches onto cable needle and hold in front, purl two, knit two from cable needle",
	},
	_2x2rpc: {
		name: "2/2 right purl cross",
		abbreviation: "2/2rpc",
		width: 4,
		symbol: "--//",
		description: "slip two stitches onto cable needle and hold in back, knit two, purl two from cable needle",
	},
	_3x3lc: {
		name: "3/3 left cross",
		abbreviation: "3/3lc",
		width: 6,
		symbol: "\\\\\\***",
		description:
			"slip three stitches onto cable needle and hold in front, knit three, knit three from cable needle",
	},
	_3x3rc: {
		name: "3/3 right cross",
		abbreviation: "3/3rc",
		width: 6,
		symbol: "***///",
		description: "slip three stitches onto cable needle and hold in back, knit three, knit three from cable needle",
	},
};
