import { stitches } from "./stitches";

export const testProject = {
	projectName: "test project 1",
	currentProjectRow: 1,
	blocks: [
		{
			currentBlockRow: 1,
			// blockName: "block 1",
			stitches: [
				[stitches.k, stitches.p, stitches.k],
				[stitches.p, stitches.k, stitches.p],
			],
		},
		{
			currentBlockRow: 1,
			// blockName: "panel a",
			stitches: [
				// "panel a" from handsome chris sweater pattern
				[stitches.p, stitches._2x1rpc, stitches._2x1lpc, stitches._2x1rpc, stitches._2x1lpc, stitches.p],
				[
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.k,
				],
				[
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches._2x2rc,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
				],
				[
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.k,
				],
				[stitches.p, stitches._2x1lpc, stitches._2x1rpc, stitches._2x1lpc, stitches._2x1rpc, stitches.p],
				[
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
				],
				[
					stitches.p,
					stitches.p,
					stitches._2x2lc,
					stitches.p,
					stitches.p,
					stitches._2x2lc,
					stitches.p,
					stitches.p,
				],
				[
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
				],
			],
		},
		{
			currentBlockRow: 1,
			blockName: "panel b",
			stitches: [
				// "panel b" from handsome chris sweater pattern
				[stitches.p, stitches._3x3rc, stitches.p, stitches.p, stitches._3x3lc, stitches.p],
				[
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
				],
				[
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.k,
					stitches.p,
				],
				[
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
					stitches.k,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.p,
					stitches.k,
				],
			],
		},
		{
			currentBlockRow: 1,
			stitches: [
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
				],
				[
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
				],
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
				],
			],
		},
		{
			currentBlockRow: 1,
			stitches: [
				[
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
				],
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
				],
				[
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
				],
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
				],
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
				],
				[
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
				],
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
				],
				[
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
				],
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
				],
				[
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
					{ name: "knit", abbreviation: "k", symbol: "*", description: "knit 1", width: 1 },
					{ name: "purl", abbreviation: "p", symbol: "-", description: "purl 1", width: 1 },
				],
			],
		},
	],
};
