// import { stitches } from "./stitches";
import { testBlocks } from "./testBlocks";

export const testProject = {
	// projectName: "test project 1",
	// currentProjectRow: 1,
	// blocks: [
	// 	{
	// 		currentBlockRow: 1,
	// 		blockName: "panel a",
	// 		stitches: [
	// 			// "panel a" from handsome chris sweater pattern
	// 			[stitches.p, stitches._2x1rpc, stitches._2x1lpc, stitches._2x1rpc, stitches._2x1lpc, stitches.p],
	// 			[
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 			],
	// 			[
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._2x2rc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 			],
	// 			[
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 			],
	// 			[stitches.p, stitches._2x1lpc, stitches._2x1rpc, stitches._2x1lpc, stitches._2x1rpc, stitches.p],
	// 			[
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 			],
	// 			[
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._2x2lc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._2x2lc,
	// 				stitches.p,
	// 				stitches.p,
	// 			],
	// 			[
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 			],
	// 		],
	// 	},
	// 	{
	// 		currentBlockRow: 1,
	// 		blockName: "panel b",
	// 		stitches: [
	// 			// "panel b" from handsome chris sweater pattern
	// 			[stitches.p, stitches._3x3rc, stitches.p, stitches.p, stitches._3x3lc, stitches.p],
	// 			[
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 			],
	// 			[
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 			],
	// 			[
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 			],
	// 		],
	// 	},
	// 	{
	// 		currentBlockRow: 1,
	// 		blockName: "panel c",
	// 		stitches: [
	// 			[
	// 				stitches.ktbl,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.ktbl,
	// 			],
	// 			[
	// 				stitches.ptbl,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.ptbl,
	// 			],
	// 			[
	// 				stitches.ktbl,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1lpc,
	// 				stitches._1x1rpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1lpc,
	// 				stitches._1x1rpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1lpc,
	// 				stitches._1x1rpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.ktbl,
	// 			],
	// 			[
	// 				stitches.ptbl,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.ptbl,
	// 			],
	// 			[
	// 				stitches.ktbl,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1lpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rpc,
	// 				stitches._1x1lpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rpc,
	// 				stitches._1x1lpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.ktbl,
	// 			],
	// 			[
	// 				stitches.ptbl,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.ptbl,
	// 			],
	// 			[
	// 				stitches.ktbl,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.ktbl,
	// 			],
	// 			[
	// 				stitches.ptbl,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.ptbl,
	// 			],
	// 			[
	// 				stitches.ktbl,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1lpc,
	// 				stitches._1x1rpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1lpc,
	// 				stitches._1x1rpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1lpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.ktbl,
	// 			],
	// 			[
	// 				stitches.ptbl,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.ptbl,
	// 			],
	// 			[
	// 				stitches.ktbl,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rpc,
	// 				stitches._1x1lpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rpc,
	// 				stitches._1x1lpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches._1x1rpc,
	// 				stitches._1x1lpc,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.ktbl,
	// 			],
	// 			[
	// 				stitches.ptbl,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.p,
	// 				stitches.p,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.k,
	// 				stitches.ptbl,
	// 			],
	// 		],
	// 	},
	// 	{
	// 		currentBlockRow: 1,
	// 		blockName: "panel d",
	// 		stitches: [
	// 			[stitches.p, stitches._3x3lc, stitches.p],
	// 			[stitches.k, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.k],
	// 			[stitches.p, stitches.k, stitches.k, stitches.k, stitches.k, stitches.k, stitches.k, stitches.p],
	// 			[stitches.k, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.k],
	// 		],
	// 	},
	// 	{
	// 		currentBlockRow: 1,
	// 		blockName: "panel e",
	// 		stitches: [
	// 			[stitches.p, stitches._3x3rc, stitches.p],
	// 			[stitches.k, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.k],
	// 			[stitches.p, stitches.k, stitches.k, stitches.k, stitches.k, stitches.k, stitches.k, stitches.p],
	// 			[stitches.k, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.p, stitches.k],
	// 		],
	// 	},
	// ],
	projectName: "test project 1",
	currentProjectRow: 1,
	mode: "chart",
	settings: {
		theme: "system",
		stitchDisplay: "symbol",
		stitchTipMode: "hover",
		directionsOverlayMode: "simple",
		showDeleteRowConfirmation: true,
		showDeleteBlockConfirmation: true,
		autoCloseStitchMenu: true,
		showTutorial: false,
		showWelcome: false,
	},
	blocks: [
		// {
		// 	currentBlockRow: 1,
		// 	blockName: "panel a",
		// 	stitches: testBlocks.blockA,
		// },
		// {
		// 	currentBlockRow: 1,
		// 	blockName: "panel b",
		// 	stitches: testBlocks.blockB,
		// },
		{
			currentBlockRow: 1,
			blockName: "panel a",
			stitches: testBlocks.blockA,
		},
		{
			currentBlockRow: 1,
			blockName: "panel b",
			stitches: testBlocks.blockB,
		},
		{
			currentBlockRow: 1,
			blockName: "panel c",
			stitches: testBlocks.blockC,
		},
		{
			currentBlockRow: 1,
			blockName: "panel b",
			stitches: testBlocks.blockB,
		},
		{
			currentBlockRow: 1,
			blockName: "panel a",
			stitches: testBlocks.blockA,
		},
		// {
		// 	currentBlockRow: 1,
		// 	blockName: "panel b",
		// 	stitches: testBlocks.blockB,
		// },
		// {
		// 	currentBlockRow: 1,
		// 	blockName: "panel a",
		// 	stitches: testBlocks.blockA,
		// },
	],
};
